djdeneme/auths/urls.py
from django.urls import path, re_path
from .views import register,user_login , user_logout , user_profile ,user_settings , user_password_change , my_favorites


urlpatterns =[
    path("register/" , register , name="register"),
    path("login/" , user_login , name="user-login"),
    path("logout/" , user_logout , name="user-logout"),
    path("settings/", user_settings , name="user-settings"),
    path("settings/change-password/" , user_password_change , name="user-password-change"),
    re_path(r'^(?P<username>[\w-]+)/$' , user_profile , name="user-profile"),
    re_path(r'^(?P<username>[\w-]+)/my_favorites/$', my_favorites , name="my-favorites")
]

djdeneme/djdeneme/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from blogmy import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("posts/", include("blogmy.urls")),
    path("auths/", include("auths.urls")),
    path("following/", include("following.urls")),
    path("fast/" , include("fastmessaging.urls")),
    path('iletisim/', views.iletisim, name="iletisim"),
    path('deneme/', views.deneme, name='deneme'),
    path('deneme-ajax/', views.deneme_ajax, name='denemeajax'),
    path('deneme-ajax-2/', views.deneme_ajax2, name='denemeajax2'),
    path('mylist/', views.mylist, name='mylist'),
    path('chatdeneme/', views.chtdeneme , name='chtdeneme')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djdeneme/static_root/auths/urls.py
from django.urls import path, re_path
from .views import register,user_login , user_logout , user_profile ,user_settings , user_password_change , my_favorites


urlpatterns =[
    path("register/" , register , name="register"),
    path("login/" , user_login , name="user-login"),
    path("logout/" , user_logout , name="user-logout"),
    path("settings/", user_settings , name="user-settings"),
    path("settings/change-password/" , user_password_change , name="user-password-change"),
    re_path(r'^(?P<username>[\w-]+)/$' , user_profile , name="user-profile"),
    re_path(r'^(?P<username>[\w-]+)/my_favorites/$', my_favorites, name="my-favorite"),
]

djdeneme/static_root/blogmy/urls.py
from django.urls import path, re_path
from .views import post_list, post_create, post_delete, post_update, post_detail,add_comment , add_or_remove_favorite

urlpatterns = [
    path("", post_list, name='post-list'),
    re_path('post_create/', post_create, name="post-create"),
    re_path(r'^post_detail/(?P<slug>[\w-]+)/$', post_detail, name="post-detail"),
    re_path(r'^post_update/(?P<slug>[\w-]+)/$', post_update, name="post-update"),
    re_path(r'^post_delete/(?P<slug>[\w-]+)/$', post_delete, name="post-delete"),
    re_path(r'^add_comment/(?P<slug>[\w-]+)/$', add_comment, name="add-comment"),
    re_path(r'^add_remove_favorite/(?P<slug>[\w-]+)/$', add_or_remove_favorite, name="add-remove-favorite"),

]

djdeneme/auths/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    SEX = ((None , 'Lütfen Birini Seçin') , ('hicbiri' , 'Belirtmek İstemiyorum'),('erkek' , 'ERKEK') , ('kadın' , 'KADIN'))
    user = models.OneToOneField(User , null=True , blank=False , verbose_name='User', on_delete=models.CASCADE)
    bio = models.TextField(max_length=1000 , verbose_name="Hakkımda" , blank=True , null=True)
    profile_photo = models.ImageField(null=True , blank=True , verbose_name='Profil Fotoğrafı')
    dogum_tarihi = models.DateField(null=True , blank=True , verbose_name='Doğum Tarihi')
    sex = models.CharField(choices=SEX , blank=True , null=True , verbose_name='Cinsiyet' , max_length=22 )

    class Meta:
        verbose_name_plural = 'Kullanici Profilleri'

    def get_screen_name(self):
        user = self.user
        if user.get_full_name():
            return user.get_full_name()
        return user.username

    def get_user_profile_url(self):
        username = self.user.username
        url = reverse('user_profile' , kwargs={'username':username})
        return url

    def get_user_full_name(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        return None

    def get_profile_photo(self):
        if self.profile_photo:
            return self.profile_photo.url
        return "/static/img/default.png"

    def __str__(self):
        return "{} Profile".format(self.get_screen_name())


def create_profile(sender , created , instance , **kwargs):
    if created :
        UserProfile.objects.create(user = instance)


post_save.connect(create_profile, sender = User)

djdeneme/static_root/auths/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    SEX = ((None , 'Lütfen Birini Seçin') , ('hicbiri' , 'Belirtmek İstemiyorum'),('erkek' , 'ERKEK') , ('kadın' , 'KADIN'))
    user = models.OneToOneField(User , null=True , blank=False , verbose_name='User', on_delete=models.CASCADE)
    bio = models.TextField(max_length=1000 , verbose_name="Hakkımda" , blank=True , null=True)
    profile_photo = models.ImageField(null=True , blank=True , verbose_name='Profil Fotoğrafı')
    dogum_tarihi = models.DateField(null=True , blank=True , verbose_name='Doğum Tarihi')
    sex = models.CharField(choices=SEX , blank=True , null=True , verbose_name='Cinsiyet' , max_length=22 )

    class Meta:
        verbose_name_plural = 'Kullanici Profilleri'

    def get_screen_name(self):
        user = self.user
        if user.get_full_name():
            return user.get_full_name()
        return user.username

    def get_user_profile_url(self):
        username = self.user.username
        url = reverse('user_profile' , kwargs={'username':username})
        return url

    def get_user_full_name(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        return None

    def get_profile_photo(self):
        if self.profile_photo:
            return self.profile_photo.url
        return "/static/img/default.png"

    def __str__(self):
        return "{} Profile".format(self.get_screen_name())


def create_profile(sender , created , instance , **kwargs):
    if created :
        UserProfile.objects.create(user = instance)


post_save.connect(create_profile, sender = User)

djdeneme/static_root/blogmy/models.py
from django.db import models
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from uuid import uuid4
import os

def upload_to(instance, filename):
    uzanti = filename.split(".")[-1]
    new_name = "{}.{}".format(str(uuid4()),uzanti)
    unique_id = instance.unique_id
    return os.path.join("blog", unique_id , new_name)


# Create your models here.
class myblogger(models.Model):
    user = models.ForeignKey(User,default=1 , null=True , verbose_name='user' , on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=False, null=True, verbose_name="Başlık giriniz",
                             help_text="Buraya başlık girilir.")

    icerik = models.TextField(max_length=1000, blank=False, null=True, verbose_name="içerik giriniz.")

    Yayin_Taslak = ((None , "Lütfen birini seçin") ,("yayin" , "YAYIN") , ("taslak" , "TASLAK"))

    yayin_taslak = models.CharField(choices=Yayin_Taslak, max_length=6 , null=True , blank=False)

    image = models.ImageField(default = "deadpool_7.jpg", upload_to = upload_to  , blank=True, verbose_name="Resim" , null=True)

    unique_id = models.CharField(max_length=100 , null=True ,editable=True)

    slug = models.SlugField(null=True, unique=True, editable=False)

    created_date = models.DateField(auto_now_add=True, auto_now=False)

    class Meta:
        verbose_name_plural = "Gönderiler"
        ordering = ['-id']

    def __str__(self):
        return "{} , {}".format(self.title , self.user)

    def get_added_favorite_user(self):
        return self.favorite_blog.values_list('user__username' , flat=True)

    def get_yayin_taslak_html(self):
        if self.yayin_taslak == "taslak":
            return '<span class="label label-danger">{}</span>'.format(self.get_yayin_taslak_display())
        return '<span class="label label-success">{}</span>'.format(self.get_yayin_taslak_display())

    def comment_count(self):
        yorum_sayisi = self.comment.count()
        if yorum_sayisi > 0:
            return yorum_sayisi
        else:
            return "Henüz yorum yok"

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'slug': self.slug})

    def get_image(self):
        if self.image:
            return self.image.url
        else:
            return "/media/deadpool_7.jpg" # eski postlara default resim döndürür

    def get_unique_slug(self):
        sayi = 0
        slug = slugify(self.title)
        new_slug = slug
        while myblogger.objects.filter(slug=new_slug).exists():
            sayi += 1
            new_slug = "{}-{}".format(slug, sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            new_unique_key = str(uuid4())
            self.unique_id = new_unique_key
            self.slug = self.get_unique_slug()
        else:
            blog = myblogger.objects.get(slug=self.slug)
            if blog.title != self.title:
                self.slug = self.get_unique_slug()
        super(myblogger, self).save(*args, **kwargs)

    def get_comment(self):
        return self.comment.all()



class Comment(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE, null=True , related_name='comment')
    blog = models.ForeignKey(myblogger , on_delete=models.CASCADE , null=True , related_name="comment")
    icerik = models.TextField(max_length=300 , verbose_name='Yorum' , blank=False , null=True ,)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name_plural = "Yorumlar"
    def __str__(self):
        return "%s %s"%(self.user, self.blog)

    def get_screen_name(self):
        if self.user.first_name:
            return "{}".format(self.user.get_full_name())
        return self.user.username


class FavoriteBlog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='favorite_blog')
    blog = models.ForeignKey(myblogger, on_delete=models.CASCADE, null=True, related_name="favorite_blog")

    class Meta:
        verbose_name_plural = "Favorilerim"

    def __str__(self):
        return "%s %s" % (self.user, self.blog)

djdeneme/static_root/following/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Following(models.Model):
    follower = models.ForeignKey(User ,related_name="follower", null=True , verbose_name="Takip eden Kullanıcı" , on_delete=models.CASCADE)
    followed = models.ForeignKey(User ,related_name="followed", null=True , verbose_name="Takip edilen kullanıcı" , on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="Takipleşme sistemi"

    def __str__(self):
        return "{} kullanıcısı {} adlı kullanıcıyı takip etti.".format(self.follower.username,self.followed.username)

    @classmethod
    def follow(cls,follower,followed):
        cls.objects.create(follower=follower,followed=followed)

    @classmethod
    def unfollow(cls,follower,followed):
        cls.objects.filter(follower=follower,followed=followed).delete()

    @classmethod
    def is_user_following(cls,follower,followed):
        return cls.objects.filter(follower=follower , followed=followed).exists()

    @classmethod
    def user_followers_followeds(cls,user):
        data = {'takip_edilenler':0 , 'takipciler':0}
        takip_edilenler = cls.objects.filter(follower=user).count()
        takipciler = cls.objects.filter(followed=user).count()

        data.update({'takip_edilenler':takip_edilenler , 'takipciler':takipciler})
        return data

    @classmethod
    def get_followers(cls,user):
        #Kullanıcının takipçilerini listeler.
        return cls.objects.filter(followed=user)

    @classmethod
    def get_followings(cls, user):
        # Kullanıcının takip ettiği kullanıcıları listeler.
        return cls.objects.filter(follower=user)

    @classmethod
    def get_followed_username(cls,user):
        follewedes = cls.get_followings(user)
        return follewedes.values_list('followed__username' , flat=True)

djdeneme/static_root/static_root/auths/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    SEX = ((None , 'Lütfen Birini Seçin') , ('hicbiri' , 'Belirtmek İstemiyorum'),('erkek' , 'ERKEK') , ('kadın' , 'KADIN'))
    user = models.OneToOneField(User , null=True , blank=False , verbose_name='User', on_delete=models.CASCADE)
    bio = models.TextField(max_length=1000 , verbose_name="Hakkımda" , blank=True , null=True)
    profile_photo = models.ImageField(null=True , blank=True , verbose_name='Profil Fotoğrafı')
    dogum_tarihi = models.DateField(null=True , blank=True , verbose_name='Doğum Tarihi')
    sex = models.CharField(choices=SEX , blank=True , null=True , verbose_name='Cinsiyet' , max_length=22 )

    class Meta:
        verbose_name_plural = 'Kullanici Profilleri'

    def get_screen_name(self):
        user = self.user
        if user.get_full_name():
            return user.get_full_name()
        return user.username

    def get_user_profile_url(self):
        username = self.user.username
        url = reverse('user_profile' , kwargs={'username':username})
        return url

    def get_user_full_name(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        return None

    def get_profile_photo(self):
        if self.profile_photo:
            return self.profile_photo.url
        return "/static/img/default.png"

    def __str__(self):
        return "{} Profile".format(self.get_screen_name())


def create_profile(sender , created , instance , **kwargs):
    if created :
        UserProfile.objects.create(user = instance)


post_save.connect(create_profile, sender = User)

djdeneme/static_root/static_root/following/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Following(models.Model):
    follower = models.ForeignKey(User ,related_name="follower", null=True , verbose_name="Takip eden Kullanıcı" , on_delete=models.CASCADE)
    followed = models.ForeignKey(User ,related_name="followed", null=True , verbose_name="Takip edilen kullanıcı" , on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="Takipleşme sistemi"

    def __str__(self):
        return "{} kullanıcısı {} adlı kullanıcıyı takip etti.".format(self.follower.username,self.followed.username)

    @classmethod
    def follow(cls,follower,followed):
        cls.objects.create(follower=follower,followed=followed)

    @classmethod
    def unfollow(cls,follower,followed):
        cls.objects.filter(follower=follower,followed=followed).delete()

    @classmethod
    def is_user_following(cls,follower,followed):
        return cls.objects.filter(follower=follower , followed=followed).exists()

    @classmethod
    def user_followers_followeds(cls,user):
        data = {'takip_edilenler':0 , 'takipciler':0}
        takip_edilenler = cls.objects.filter(follower=user).count()
        takipciler = cls.objects.filter(followed=user).count()

        data.update({'takip_edilenler':takip_edilenler , 'takipciler':takipciler})
        return data

    @classmethod
    def get_followers(cls,user):
        #Kullanıcının takipçilerini listeler.
        return cls.objects.filter(followed=user)

    @classmethod
    def get_followings(cls, user):
        # Kullanıcının takip ettiği kullanıcıları listeler.
        return cls.objects.filter(follower=user)

    @classmethod
    def get_followed_username(cls,user):
        follewedes = cls.get_followings(user)
        return follewedes.values_list('followed__username' , flat=True)

djdeneme/static_root/static_root/static_root/static_root/templates/auths/profile/myfavorites.html
{% extends 'auths/profile/user_profile_base.html' %}
{% load static %}

{% block profil_icerik %}
    <div class="row col-lg-12 col-lg-offset-3">

     {% for post in user.favorite_blog.all %}

            <table>
                <tr><h2><a
                        href="{{ post.blog.get_absolute_url }}"> {{ post.blog.title  }}</a>&nbsp;
                </h2></tr>
                {% if post.blog.get_image %}
                    <div class="row "><img src="{{ post.blog.get_image }}" width="500" height="250"></div>
                {% endif %}
                <tr><h3>{{ post.blog.icerik| truncatechars:250 }} -- <span
                        class="glyphicon glyphicon-time"></span>{{ post.blog.created_date }}</h3></tr>

            </table>

        {% endfor %}
    </div>
{% endblock %}

djdeneme/static_root/static_root/static_root/static_root/templates/auths/profile/password_change.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Ayarlar
{% endblock %}

{% block icerik %}
    <div class="row" style="padding-top: 50px">
        <div class="col-lg-8 pull-center">
        <div>
            <ul class="col-lg-offset-2 active" >
                <li role="presentation" class="active"><a href="{% url 'user-settings' %}">Profili Düzenle</a></li>
                <li role="presentation" class="active"><a href="{% url 'user-password-change' %}">Şifreni Değiştir</a></li>
            </ul>

        </div>
            <form action="{% url 'user-password-change' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="row">
                        <div class=" col-lg-offset-4">
                            <div class="form-group">
                                <div class="col-lg-2">
                                    {{ field.label_tag }}
                                </div>
                                <div class="col-lg-4">
                                    {{ field }}
                                </div>

                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>

                        </div>

                    </div>
                {% endfor %}
            <br>
                <div class="row col-lg-offset-7"><input type="submit" value="Kaydet " class="btn btn-success"></div>
            </form>
        </div>
    </div>

{% endblock %}

djdeneme/static_root/static_root/static_root/static_root/templates/auths/profile/settings.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Ayarlar
{% endblock %}

{% block icerik %}
    <div class="row" style="padding-top: 50px">
        <div class="col-lg-offset-2">
            <table class="text-center table-bordered active" style="width: 200px;height: 100px; ">
                <tr>
                    <td><a href="{% url 'user-settings' %}">Profili Düzenle</a></td>
                </tr>
                <tr >
                    <td><a href="{% url 'user-password-change' %}">Şifreni Değiştir</a></td>
                </tr>
            </table>
        </div>
        <div class="col-lg-8 pull-center">
            <form action="{% url 'user-settings' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="row">
                        <div class=" col-lg-offset-4">
                            <div class="form-group">
                                <div class="col-lg-2">
                                    {{ field.label_tag }}
                                </div>
                                <div class="col-lg-4">
                                    {{ field }}
                                </div>

                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>

                        </div>

                    </div>
                {% endfor %}
                <br>
                <div class="row col-lg-offset-7"><input type="submit" value="Kaydet " class="btn btn-success"></div>
            </form>
        </div>
    </div>

{% endblock %}

djdeneme/static_root/static_root/static_root/static_root/templates/auths/profile/user_profile.html
{% extends 'auths/profile/user_profile_base.html' %}
{% load static %}

{% block profil_icerik %}
    <div class="row col-lg-12 col-lg-offset-3">
        {% for post in user.myblogger_set.all %}
            <table>
                <tr><h2><a
                        href="{{ post.get_absolute_url }}"> {{ post.title }}</a>&nbsp;
                </h2></tr>
                {% if post.get_image %}
                    <div class="row "><img src="{{ post.get_image }}" width="500" height="250"></div>
                {% endif %}
                <tr><h3>{{ post.icerik| truncatechars:250 }} -- <span
                        class="glyphicon glyphicon-time"></span>{{ post.created_date }}</h3></tr>

            </table>

        {% endfor %}

    </div>
{% endblock %}

djdeneme/static_root/static_root/static_root/static_root/templates/auths/profile/user_profile_base.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ user.userprofile.get_screen_name }}
{% endblock %}

{% block ust_icerik %}
    <script rel="script" type="text/javascript">
        $(document).ready(function () {
            $('#follower_counts').on('click', '.follow-button', function () {
                var $this = $(this);
                var $modal = $('#profile_following_modal');
                var $follow_type = $this.attr('follow_type');
                var $username = $this.attr('username');
                var $url = $this.attr('url');
                $modal.attr('follow_type', $follow_type);
                if ($follow_type === "followers") {
                    $('#profile_modal_title').html('Takipçiler');
                } else if ($follow_type === "followedes") {
                    $('#profile_modal_title').html('Takip edilenler');
                }

                //ajax request
                $.ajax({
                    url: $url,
                    type: "GET",
                    dataType: "json",
                    data: {'username': $username},
                    success: function (data) {
                        console.log(data.html);
                        $(".modal-body").html(data.html);
                        $modal.modal('show');
                    }
                })


            });


            $('#follow_unfollow_button').click(function () {
                var $this = $(this)
                var url = $this.attr('url');
                var $follower = $this.attr('follower');
                var $followed = $this.attr('followed');
                var $data = {follower_username: $follower, followed_username: $followed};
                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: "json",
                    data: $data,
                    success: function (data) {
                        if (data.is_valid) {
                            $this.html(data.msg);
                            $("#follower_counts").html(data.html);
                        }
                    }
                })
            });
            $('#profile_following_modal').on('click', '.modal-following-button', function () {
                var $this = $(this);
                var $modal = $(this.closest(".modal"));
                var $follow_type = $modal.attr('follow_type');
                var $modal_body = $this.closest(".modal-body");
                var $owner = $modal.attr('owner');
                var $span = $this.closest("div").find('span');
                var takip_edilen = $span.attr('takip_edilen');
                var takip_eden = $span.attr('takip_eden');
                var url = "{% url 'modal-follow-unfollow' %}";
                var data = {
                    owner: $owner,
                    follow_type: $follow_type,
                    follower_username: takip_eden,
                    followed_username: takip_edilen
                };
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    data: data,
                    success: function (data) {
                        if (data.owner) {
                            $modal_body.html(data.html);
                            $('#follower_counts').html(data.html_counts);
                        } else {
                            if (data.takip_durum) {
                                $this.removeClass('btn-success');
                                $this.addClass('btn-danger');
                            } else {
                                $this.removeClass('btn-danger');
                                $this.addClass('btn-success');
                            }
                            $this.html(data.msg)
                        }

                    }
                })
            })
        });
    </script>

{% endblock %}

{% block icerik %}

    <div class="page-content page-container" id="page-content">
        <div class="padding">
            <div class="row container d-flex justify-content-center col-lg-9 col-lg-offset-2">
                <div class="col-xl-2 col-md-10">
                    <div class="card user-card-full">
                        <div class="row m-l-0 m-r-0">
                            <div class="col-sm-4 bg-c-lite-green">
                                <div class="card-block text-center text-white">
                                    <div class="m-b-25 "><img src="{{ user.userprofile.get_profile_photo }}"
                                                              class="profile-img img-radius"
                                                              alt="User-Profile-Image"></div>
                                    <h3><b>{{ user.username|safe }}</b></h3>
                                    <h4><p>{{ user.userprofile.get_user_full_name }}</p></h4>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="card-block">
                                    <h5 class="m-b-20 p-b-5 b-b-default f-w-600">Biography</h5>
                                    <div class="row">
                                        <div class="col-sm-12" style="font-family: 'Arial'">
                                            <span class="f-w-400">{{ user.userprofile.bio }}</span>
                                        </div>
                                    </div>
                                    <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Projects</h6>
                                    <div class="row">
                                        {% include 'auths/profile/include/following/following_modal.html' %}

                                        <div class="col-sm-6">
                                            <div id="follower_counts" class="row">
                                                {% include 'auths/profile/include/following/follower_counts.html' %}
                                            </div>
                                        </div>
                                        {% if request.user != user %}
                                            <div class="col-lg-offset-8">
                                                <button class="btn btn-success" id="follow_unfollow_button"
                                                        url="{% url 'follow-unfollow' %}"
                                                        follower="{{ request.user }}" followed="{{ user.username }}">
                                                    {% if is_following %}
                                                        <b>Takipten Çıkar</b>
                                                    {% else %}
                                                        <b>Takip Et</b>
                                                    {% endif %}
                                                </button>
                                            </div>
                                        {% endif %}

                                        <ul class="social-link list-unstyled m-t-40 m-b-10">
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                                                   data-original-title="facebook" data-abc="true"><i
                                                    class="mdi mdi-facebook feather icon-facebook facebook"
                                                    aria-hidden="true"></i></a></li>
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                                                   data-original-title="twitter" data-abc="true"><i
                                                    class="mdi mdi-twitter feather icon-twitter twitter"
                                                    aria-hidden="true"></i></a>
                                            </li>
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                                                   data-original-title="instagram" data-abc="true"><i
                                                    class="mdi mdi-instagram feather icon-instagram instagram"
                                                    aria-hidden="true"></i></a></li>
                                        </ul>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% if request.user == user %}
                        {% include 'auths/profile/include/owner_navbar.html' %}
                    {% else %}
                        {% include 'auths/profile/include/visitor_navbar.html' %}
                    {% endif %}
                    <div>
                        {% block profil_icerik %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}